# Generated by Django 5.1.4 on 2025-02-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_resume_kategoria_vacancy_kategoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='kategoria',
            field=models.TextField(choices=[('Tehno', 'Техно')], default='Tehno', max_length=10, null=True),
        ),
    ]
