# Generated by Django 5.1.4 on 2025-02-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_resume_kategoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='kategoria',
        ),
        migrations.AddField(
            model_name='resume',
            name='resumekategoria',
            field=models.TextField(choices=[('ProfessionalExperience', 'Професійний досвід'), ('Projects', 'Проекти')], default='ProfessionalExperience', null=True),
        ),
    ]
