# Generated by Django 5.1.4 on 2025-02-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_resume_kategoria_resume_resumekategoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='resumekategoria',
            field=models.TextField(choices=[('ProfessionalExperience', 'Професійний досвід'), ('Projects', 'Проекти')], default='Projects', null=True),
        ),
    ]
