# Generated by Django 5.1.4 on 2025-03-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_vacancy_mainvacancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='city',
            field=models.CharField(choices=[('Kyiv', 'Київ'), ('Lviv', 'Львів'), ('Odessa', 'Одеса'), ('Kharkiv', 'Харків'), ('Dnipropetrovsk', 'Дніпро'), ('Zaporizhzhia', 'Запоріжжя'), ('Cherkasy', 'Черкаси'), ('Chernivtsi', 'Чернівці'), ('Poltava', 'Полтава'), ('Vinnytsia', 'Вінниця ')], default='Lviv', max_length=100000),
        ),
    ]
