# Generated by Django 5.1.4 on 2025-03-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_vacancy_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='resume',
            field=models.TextField(max_length=10000),
        ),
    ]
