# Generated by Django 5.1.4 on 2025-03-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_vacancy_kontaktu'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='kontaktu',
            field=models.CharField(max_length=100000, null=True),
        ),
    ]
