# Generated by Django 5.1.4 on 2025-03-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_resume_kontaktu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='kontaktu',
        ),
        migrations.AddField(
            model_name='resume',
            name='resumekontaktu',
            field=models.CharField(max_length=100000, null=True),
        ),
    ]
