# Generated by Django 5.1.4 on 2025-04-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_resume_kontaktu_resume_resumekontaktu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.CharField(choices=[('GeneralSecondaryEducation', 'ЗагальноСередняОсвіта'), ('HigherEducation', 'ВищаОсвіта'), ('VocationalEducation', 'ПрофесійнаТехнічнаОсвіта')], default='GeneralSecondaryEducation', max_length=100000),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='kategoria',
            field=models.TextField(choices=[('Tehno', 'Техно'), ('Dergavna', 'Державна робота')], default='Tehno', max_length=10000, null=True),
        ),
    ]
