# Generated by Django 5.1.4 on 2025-04-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_vacancy_education_alter_vacancy_kategoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='education',
            field=models.CharField(choices=[('GeneralSecondaryEducation', 'ЗагальноСередняОсвіта'), ('HigherEducation', 'ВищаОсвіта'), ('VocationalEducation', 'ПрофесійнаТехнічнаОсвіта')], default='GeneralSecondaryEducation', max_length=10000, null=True),
        ),
    ]
