# Generated by Django 5.1.4 on 2025-04-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_vacancy_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='mainresume',
            field=models.CharField(max_length=100000, null=True),
        ),
    ]
